### PR TITLE
[EAGLE-986] HBaseStorage unable to deserialize Deserialize from java

### PR DESCRIPTION
**Pull request by r7raul1984**
[EAGLE-986] HBaseStorage unable to deserialize  from java object bytes

- recover allocatedMB type from int to long

https://issues.apache.org/jira/browse/EAGLE-986

### CODE REVIEW

**Comment by baibaichen** [comment]
@r7raul1984 please make sure **long** is compatible with **int**.

**Comment by qingwen220** [comment]
LGTM

**Comment by baibaichen** [comment]
@r7raul1984 told me  that long is not compatible with int, so even we revert it to long, we will still get deserialization issue. 

@qingwen220  how does ebay deploy eagle? Did you clean HBase data after changing **long** to **int**?

**Comment by r7raul1984** [comment]
@qingwen220 @zombieJ  pls help review

**Comment by zombieJ** [comment]
@r7raul1984 , Could you pls use `QUERY_LIST` instead of new const `QUERY_MR_HISTORY_JOBS`?

**Comment by r7raul1984** [comment]
@zombieJ  OK

**Comment by zombieJ** [comment]
LGTM

**Pull request closed without merging**
