### PR TITLE
HBase Naming that unify `Hbase` and `HBase` into `HBase`

### PR DESCRIPTION
**Pull request by asdf2014**
HBase Naming that unify `Hbase` and `HBase` into `HBase`

(https://issues.apache.org/jira/browse/EAGLE-992)

### CODE REVIEW

**Comment by jhsenjaliya** [comment]
@asdf2014, Can you please look into why this is failing and fix this PR ? Thanks

**Comment by asdf2014** [comment]
@jhsenjaliya Hi, jhsenjaliya. I am glad to fix the problem in PR, but i got the `404` page in Jinkens when i visit the [url](https://builds.apache.org/job/incubator-eagle-pr-reviewer/1773/)...
image

**Comment by jhsenjaliya** [comment]
@asdf2014 , please squash commit and force push it here in the same branch that should re-trigger the jenkin job.  that job is probably old and hence can not access it. Thanks

**Comment by asdf2014** [comment]
@jhsenjaliya Already done.

**Comment by jhsenjaliya** [comment]
@asdf2014 please add [MINOR] tag in pr title since there is not jira for this.

**Comment by asdf2014** [comment]
@jhsenjaliya Okey, i got it.

**Pull request closed without merging**
