### PR TITLE
Docker updates for eagle 0.5

### PR DESCRIPTION
**Pull request by jhsenjaliya**
This docker image is for eagle 0.5

There is still an issue where namenode process dies sometimes.
creating this PR to get the review started....

### CODE REVIEW

**Comment by jhsenjaliya** [comment]
@qinzhaokun, @haoch  can u please review this ? its working fine now

**Comment by haoch** [comment]
@jhsenjaliya how could I quickly have a try about the docker image? some guide like building/quick starting?

**Comment by jhsenjaliya** [comment]
Hi Hao, the process i have kept similar, I was using "docker for mac" which has some known issues.
most likely docker image building will fail at running YUM install, so you will have to change the storage-driver of docker from AUFS to overlayFS , more detail on how to do it can be found here under “Configure Docker with the overlay/overlay2 storage driver”: Configure Docker with the overlay/overlay2 storage driver

Following 2 commands should get you docker image and create container for eagle with services.
./bin/eagle-docker.sh build
./bin/eagle-docker.sh deploy

**Comment by qingwen220** [comment]
LGTM

**Pull request closed without merging**
