### PR TITLE
[MINOR] Change default-rack to /default-rack

### PR DESCRIPTION
**Pull request by r7raul1984**
- Change default-rack to /default-rack

### CODE REVIEW

**Comment by qingwen220** [comment]
Why do you need this change?

**Comment by qingwen220** [comment]
At the initial design, we prefer to extract the 'exact rack info', for example,  '/rack-45' -> 'rack-45',  '/' will be removed.

**Comment by r7raul1984** [comment]
@qingwen220  Because ClusterNodeAPITopologyRackResolver use "/default-rack" .I think it will issue some problem when  you complete EAGLE-876.

**Comment by qingwen220** [comment]
It do not matter.  The node with a new rack info will replace the old one

**Pull request closed without merging**
