### PR TITLE
[EAGLE-522] Implement HOURLY_RULE for Absence Alert.

### PR DESCRIPTION
**Pull request by pkuwm**

### CODE REVIEW

**Comment by haoch** [comment]
@pkuwm there are conflicts, could you please help fix it?

**Comment by pkuwm** [comment]
@haoch Done.

**Comment by yonzhang** [comment]
@pkuwm this is important PR for absence alert, can you please add detailed description for people to learn what are the changes?

**Comment by pkuwm** [comment]
Updated description. Merged with the newest commits.

**Comment by haoch** [comment]
@pkuwm there is building error, could you pls. confirm it? If no problem, we will merge.

**Comment by pkuwm** [comment]
I don't think the failure came from my PR. From the building log, it seems the failure was caused by eagle-server. You can verify that.

**Pull request closed without merging**
